# uncomment to enable components
components:
        - frigate
        - pihole
        - caddy
        - wireguard
        - ddns
        - ssh
        - firewall

##################################################################
general:
        apex_domain: "noor.now"
        hostname: "noor"
        host_ip: 10.100.0.1         # since connection is possible only through wireguard; it's both hip and wg iface

        fileserver_root: /srv/share

        build_path: ./build
        install: /stacks/survur     # where everything non-shared will exist

        common_config_folder:       # folder with symlinks to each config (not compose)
                enable: true
                path: /stacks/cfg

##################################################################
caddy:
        fileserver:
                enable: true
                subdomain: fs
                browsable: true

##################################################################
frigate:
        subdomain:
                name: "cams"
                port: 8971
        docker:
                shm_size: "180m"
                volumes:
                        - ./config:/config
                        - ./storage:/media/frigate
                ports:
                        - "8971:8971"
                        # - "5000:5000" # Internal unauthenticated access. Expose carefully.
                        # - "8554:8554" # RTSP feeds
                        - "8555:8555/tcp" # WebRTC over tcp
                        # - "8555:8555/udp" # WebRTC over udp

        # every cam is enabled; by default each cam has audio and record
        # roles in ffmpeg section. detect defaults false if omitted
        # onvif_port is optional - omit to skip onvif for that camera
        cams:
               name:
                       login: "asd"
                       password: "asd"
                       ip: 1.1.1.1
                       stream: "stream1"
                       detect: false
                       onvif_port: 8000

##################################################################
# will use my script with duckdns
# https://github.com/Nolven/duckdns_keepup
ddns:
        bin_path: /usr/local/bin
        domain: "33"
        token: "321d12ed12"

##################################################################
pihole:
        # for webui
        subdomain:
                port: 8081
                name: pihole
                redir: /admin
        admin_pass: 12345         # USER, BE RESPONSIBLE - CHANGE
        upstream_dns: 8.8.8.8

###################################################################
wireguard:
        # interface_ip = general.host_ip
        server_mask: 24
        listen_port: 44444

###################################################################
ssh:
        port: 1488          # lazy security from bots
        permit_root_login: "yes"
        password_authentication: true

###################################################################
firewall: # nftables
        nft_file_path: /stacks/cfg/nftables.conf