services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.17.2
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000

  # mqtt:
  #   container_name: mosquitto
  #   image: eclipse-mosquitto:latest
  #   restart: unless-stopped
  #   ports:
  #     - "1883:1883"
  #   volumes:
  #     - ./mosquitto/config:/mosquitto/config
  #     - ./mosquitto/data:/mosquitto/data
  #     - ./mosquitto/log:/mosquitto/log
