mqtt:
  enabled: false

# managed by caddy
tls:
  enabled: false

# example
#go2rtc:
  # streams:
  #   name:
  #     - rtsp://name:pass@ip:554/stream1

snapshots:
  enabled: true
  clean_copy: true
  timestamp: true
  bounding_box: true
  crop: false
  # required_zones: [] # Restrict snapshots to objects that entered any of the listed zones
  retain:
    default: 10 # days
    objects:
      person: 40
  quality: 70 # 0-100

record:
  enabled: true
  expire_interval: 120 # timeout between cleanup runs (mins)
  retain:
    days: 7
    mode: all

detect:
  enabled: false
  width: 1280
  height: 720
  fps: 5
  min_initialized: 5
  max_disappeared: 25
  stationary:
    classifier: true
    interval: 50
    threshold: 50

motion:
  enabled: false
  threshold: 35
  contour_area: 25 # sensitivity: 10-high, 50-low
  improve_contrast: true

# example
#cameras:
#  cam_name:
#    detect:
#      enabled: true
#    motion:
#      enabled: true
#    ffmpeg:
#      inputs:
#        - path: rtsp://login:pass@ip:554/stream1
#          roles: # eveyr cam should have
#            - audio
#            - record
#    onvif: # each camera should have
#      host: ip
#      port: 2020
#      user: login
#      password: pass